package com.imo.backend.config.mongodb.populate.skills;

import com.imo.backend.contexts.catalog.course.Categories;
import com.imo.backend.contexts.catalog.skill.Skill;
import java.util.List;
import org.springframework.stereotype.Component;

@Component
public class StaticSkillsCatalog {
  public List<Skill> items() {
    return List.of(
        new Skill(Categories.FUNDAMENTALS, "Logica de programacao", 3),
        new Skill(Categories.FUNDAMENTALS, "Algoritmos", 3),
        new Skill(Categories.FUNDAMENTALS, "Estruturas de dados", 3),
        new Skill(Categories.FUNDAMENTALS, "Pensamento computacional", 3),
        new Skill(Categories.FUNDAMENTALS, "Logica booleana", 2),
        new Skill(Categories.FUNDAMENTALS, "Resolucao de problemas", 2),
        new Skill(Categories.FUNDAMENTALS, "Versionamento com Git", 2),
        new Skill(Categories.FUNDAMENTALS, "Linha de comando", 1),
        new Skill(Categories.FUNDAMENTALS, "Boas praticas de codigo", 2),
        new Skill(Categories.FUNDAMENTALS, "Testes automatizados", 1),
        new Skill(Categories.DEV_WEB, "HTML", 2),
        new Skill(Categories.DEV_WEB, "CSS", 2),
        new Skill(Categories.DEV_WEB, "JavaScript", 3),
        new Skill(Categories.DEV_WEB, "TypeScript", 3),
        new Skill(Categories.DEV_WEB, "React", 3),
        new Skill(Categories.DEV_WEB, "Acessibilidade web", 2),
        new Skill(Categories.DEV_WEB, "Consumo de APIs", 2),
        new Skill(Categories.DEV_WEB, "Responsividade", 2),
        new Skill(Categories.DEV_WEB, "Gerenciamento de estado", 2),
        new Skill(Categories.DEV_WEB, "Node.js", 3),
        new Skill(Categories.DATA, "SQL", 3),
        new Skill(Categories.DATA, "Modelagem de dados", 3),
        new Skill(Categories.DATA, "ETL", 2),
        new Skill(Categories.DATA, "Analise exploratoria de dados", 2),
        new Skill(Categories.DATA, "Estatistica descritiva", 2),
        new Skill(Categories.DATA, "Visualizacao de dados", 2),
        new Skill(Categories.DATA, "Python para dados", 3),
        new Skill(Categories.DATA, "Pandas", 2),
        new Skill(Categories.DATA, "Data Warehouse", 2),
        new Skill(Categories.DATA, "Qualidade de dados", 2),
        new Skill(Categories.CLOUD, "Docker", 2),
        new Skill(Categories.CLOUD, "Kubernetes", 3),
        new Skill(Categories.CLOUD, "AWS", 3),
        new Skill(Categories.CLOUD, "Azure", 2),
        new Skill(Categories.CLOUD, "Google Cloud", 2),
        new Skill(Categories.CLOUD, "Infraestrutura como codigo", 3),
        new Skill(Categories.CLOUD, "CI/CD", 2),
        new Skill(Categories.CLOUD, "Monitoramento", 2),
        new Skill(Categories.CLOUD, "Redes em nuvem", 2),
        new Skill(Categories.CLOUD, "Containers", 2),
        new Skill(Categories.SECURITY, "OWASP", 2),
        new Skill(Categories.SECURITY, "Criptografia", 3),
        new Skill(Categories.SECURITY, "Seguranca de redes", 3),
        new Skill(Categories.SECURITY, "Identity and Access Management", 2),
        new Skill(Categories.SECURITY, "Analise de vulnerabilidades", 3),
        new Skill(Categories.SECURITY, "Seguranca em APIs", 2),
        new Skill(Categories.SECURITY, "LGPD", 1),
        new Skill(Categories.SECURITY, "Secure Coding", 2),
        new Skill(Categories.SECURITY, "Resposta a incidentes", 2),
        new Skill(Categories.SECURITY, "Gestao de riscos", 2),
        new Skill(Categories.AI, "Machine Learning", 3),
        new Skill(Categories.AI, "Deep Learning", 3),
        new Skill(Categories.AI, "Processamento de linguagem natural", 2),
        new Skill(Categories.AI, "Visao computacional", 2),
        new Skill(Categories.AI, "Engenharia de prompts", 2),
        new Skill(Categories.AI, "MLOps", 2),
        new Skill(Categories.AI, "Redes neurais", 3),
        new Skill(Categories.AI, "Scikit-learn", 2),
        new Skill(Categories.AI, "LLMs", 2),
        new Skill(Categories.AI, "Avaliacao de modelos", 2),
        new Skill(Categories.DEV_MOBILE, "React Native", 3),
        new Skill(Categories.DEV_MOBILE, "Android", 3),
        new Skill(Categories.DEV_MOBILE, "iOS", 3),
        new Skill(Categories.DEV_MOBILE, "Flutter", 2),
        new Skill(Categories.DEV_MOBILE, "Kotlin", 2),
        new Skill(Categories.DEV_MOBILE, "Swift", 2),
        new Skill(Categories.DEV_MOBILE, "Gerenciamento de estado mobile", 2),
        new Skill(Categories.DEV_MOBILE, "Publicacao de apps", 1),
        new Skill(Categories.DEV_MOBILE, "Offline first", 2),
        new Skill(Categories.DEV_MOBILE, "Integracao com APIs", 2));
  }
}
