version: '3.8'

services:
  spring-app:
    image: backend-imo:latest
    ports:
      - "8080:8080"
    
  react-app:
    image: frontend-imo:latest
    ports:
      - "5173:5173"
    depends_on:
      - spring-app
