server.port=8080
spring.application.name=backend
jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key
spring.config.import=classpath:.env-dev.properties
logging.level.org.springframework.data.mongodb=DEBUG
spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB
# Envs
spring.data.mongodb.uri=${MONGO_URI}
client.url=${CLIENT_URL}
exchange_name=${EXCHANGE_NAME}
routing_key.forget_password=${ROUTING_KEY_FORGET_PASSWORD}
routing_key.confirm_email=${ROUTING_KEY_CONFIRMATION_EMAIL}
spring.rabbitmq.addresses=${RABBITMQ_ADDRESS}
# Docs
springdoc.api-docs.path=/v3/api-docs
# Basic configuration
scalar.url=http://localhost:8080/v3/api-docs
scalar.path=/docs
scalar.enabled=true
# UI customization
scalar.showSidebar=true
scalar.hideModels=false
scalar.hideTestRequestButton=false
scalar.hideSearch=false
# Theme and appearance
scalar.darkMode=false
scalar.hideDarkModeToggle=false
scalar.theme=default
scalar.layout=modern
# Document options
scalar.documentDownloadType=both
# Custom styling
scalar.customCss=body { font-family: 'Arial', sans-serif; }
