server.port=8080
spring.application.name=backend
jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key
spring.config.import=optional:classpath:.env-prod.properties
spring.data.mongodb.uri=${ATLAS_CLUSTER}
spring.data.mongodb.database=${CLUSTER_DATABASE}
client.url=${CLIENT_URL}
spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB
