server.port=8080
spring.application.name=backend
jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key
spring.config.import=classpath:.env-dev.properties
spring.data.mongodb.uri=${MONGO_URI}
client.url=${CLIENT_URL}
logging.level.org.springframework.data.mongodb=DEBUG
springdoc.api-docs.path=/docs
spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB
