# Logging
logging.level.root=${LOG_LEVEL:WARN}
logging.level.com.imo=${LOG_LEVEL:ERROR}
logging.level.org.springframework.data.mongodb=${MONGO_LOGGING:OFF}
logging.level.org.springframework.amqp=${MONGO_LOGGING:OFF}
# ---------------------------------------------------------------
# Dev tools
## Spring boot dev tools
spring.devtools.add-properties=false
## Docs
springdoc.api-docs.enabled=false
## Swagger
springdoc.swagger-ui.enabled=false
## Scalar
scalar.enabled=false
