# ----------------------------------------------------------------
# Server
spring.application.name=imo-backend
server.port=${PORT:8080}
backend.base-url=${BACKEND_BASE_URL:}
# ----------------------------------------------------------------
# Files
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=10MB
# ----------------------------------------------------------------
# Storage
storage.mode=${STORAGE_MODE:local}
storage.local.upload-dir=${STORAGE_LOCAL_UPLOAD_DIR:src/main/resources/uploads}
# ----------------------------------------------------------------
# Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
# ----------------------------------------------------------------
# MongoDB
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017}
spring.data.mongodb.database=${MONGO_DATABASE:imo}
spring.data.mongodb.auto-index-creation=true
# ----------------------------------------------------------------
# Frontend
frontend.client.url=${CLIENT_URL:http://localhost:5173}
frontend.email.confirmation.url=${EMAIL_CONFIRMATION_URL:http://localhost:5173/user/confirmar-email}
# ----------------------------------------------------------------
# RabbitMQ
spring.rabbitmq.addresses=${RABBITMQ_URI:amqp://localhost:5672}
rabbitmq.identity.exchange=${RABBITMQ_EXCHANGE:identity.events}
rabbitmq.routing.confirm_email=${RABBITMQ_ROUTING_KEY_CONFIRM_EMAIL:user.email.confirmation.requested}
rabbitmq.routing.forget_password=${RABBITMQ_ROUTING_KEY_FORGET_PASSWORD:user.password.reset.requested}
rabbitmq.queue.confirm_email=${RABBITMQ_QUEUE_CONFIRM_EMAIL:notification.email.confirmation}
rabbitmq.queue.forget_password=${RABBITMQ_QUEUE_FORGET_PASSWORD:notification.email.password-reset}
# ----------------------------------------------------------------
# S3
aws.s3.bucket=${AWS_S3_BUCKET}
aws.region=${AWS_REGION}
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
# ----------------------------------------------------------------
# E-MAIL
email.host=${EMAIL_HOST:smtp.gmail.com}
email.port=${EMAIL_PORT:587}
email.username=${EMAIL_USERNAME}
email.password=${EMAIL_PASSWORD}
# ----------------------------------------------------------------
# JWT
jwt.public.key=${JWT_PUBLIC_KEY:classpath:app.pub}
jwt.private.key=${JWT_PRIVATE_KEY:classpath:app.key}
# ---------------------------------------------------------------
# Logging (altere em prod)
logging.level.root=${LOG_LEVEL:INFO}
logging.level.com.imo=${LOG_LEVEL:DEBUG}
logging.level.org.springframework.data.mongodb=${MONGO_LOGGING:DEBUG}
logging.level.org.springframework.amqp=${MONGO_LOGGING:DEBUG}
# ---------------------------------------------------------------
# Dev tools (desative em prod)
## Spring dev tools
spring.devtools.add-properties=true
## Docs
springdoc.api-docs.enabled=true
## Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
## Scalar
scalar.enabled=true
scalar.url=/v3/api-docs
scalar.path=/docs
