name: Deploy ECS

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      concurrency-group:
        required: true
        type: string
      build-and-push:
        required: false
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    concurrency:
      group: ${{ inputs.concurrency-group }}
      cancel-in-progress: true

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build e push da imagem Docker
        if: ${{ inputs.build-and-push }}
        working-directory: backend
        env:
          ECR_URI: ${{ secrets.ECR_REPOSITORY }}
        run: |
          IMAGE_URI=$ECR_URI:${{ github.sha }}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "image=$IMAGE_URI" >> "$GITHUB_OUTPUT"
      
      - name: Definindo URI da imagem docker
        id: build-image
        run: |
            echo "image=${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}" >> "$GITHUB_OUTPUT"
        

      - name: Baixar task definition atual
        run: |
          aws ecs describe-task-definition \
            --task-definition "${{ vars.ECS_TASK_DEFINITION }}" \
            --query taskDefinition \
            > task-definition.json

      - id: render-task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ vars.ECS_CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-definition.outputs.task-definition }}
          service: ${{ vars.ECS_SERVICE }}
          cluster: ${{ vars.ECS_CLUSTER }}
          wait-for-service-stability: true