name: Backend CD Pipeline

on:
  push:
    branches: [master]
    paths:
      - "backend/**"
      - ".github/workflows/backend-cd.yml"

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: prod

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Baixa o codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login no ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build e push da imagem Docker
        working-directory: backend
        run: |
          ECR_URI=${{ secrets.ECR_REPOSITORY }}

          docker build -t $ECR_URI:${{ github.sha }} .

          docker push $ECR_URI:${{ github.sha }}
        
          



